#!/bin/bash
# ─── Setup script for CLI AI Agent on Termux ────────────────
# Run this once: bash setup.sh
# Then use the agent from anywhere: ai "your prompt"

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="$PREFIX/bin"  # Termux default bin directory

# Fallback if not on Termux
if [ -z "$PREFIX" ]; then
    BIN_DIR="$HOME/.local/bin"
    mkdir -p "$BIN_DIR"
fi

echo "🚀 Setting up CLI AI Agent..."
echo "   Agent location: $SCRIPT_DIR"
echo "   Command will be installed to: $BIN_DIR/ai"

# Install Python dependencies
echo ""
echo "📦 Installing dependencies..."
pip install -r "$SCRIPT_DIR/requirements.txt"

# Create the launcher script
cat > "$BIN_DIR/ai" << EOF
#!/bin/bash
# CLI AI Agent launcher — auto-generated by setup.sh
python "$SCRIPT_DIR/agent.py" "\$@"
EOF

chmod +x "$BIN_DIR/ai"

# Check if BIN_DIR is in PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo ""
    echo "⚠️  $BIN_DIR is not in your PATH."
    echo "   Add this line to your ~/.bashrc or ~/.zshrc:"
    echo ""
    echo "   export PATH=\"$BIN_DIR:\$PATH\""
    echo ""

    # Auto-add to bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$HOME/.bashrc"
        echo "   ✅ Added to ~/.bashrc automatically."
        echo "   Run: source ~/.bashrc"
    fi
fi

echo ""
echo "✅ Setup complete! You can now use the agent from anywhere:"
echo ""
echo "   ai                        # interactive mode"
echo "   ai \"list files here\"      # single-shot mode"
echo "   ai --yolo                 # auto-approve tool calls"
echo "   ai --model gpt-oss:120b-cloud  # different model"
echo ""
echo "⚠️  Don't forget to set your API key:"
echo "   export OLLAMA_API_KEY=your_key_here"
echo ""
